-- Maak de employees-tabel
CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    role_id NUMBER
);

-- Voeg foreign key toe naar roles
ALTER TABLE employees ADD CONSTRAINT fk_employees_role
    FOREIGN KEY (role_id) REFERENCES roles(id);


-- Voeg employees toe met verschillende rollen
INSERT INTO employees (first_name, last_name, email, role_id)
VALUES ('Alice', 'Jansen', 'alice.jansen@example.com', (SELECT id FROM roles WHERE role_name = 'admin'));

INSERT INTO employees (first_name, last_name, email, role_id)
VALUES ('Bob', 'Peters', 'bob.peters@example.com', (SELECT id FROM roles WHERE role_name = 'user'));

INSERT INTO employees (first_name, last_name, email, role_id)
VALUES ('Charlie', 'Vermeer', 'charlie.vermeer@example.com', (SELECT id FROM roles WHERE role_name = 'guest'));

COMMIT;
